# Generated by Django 5.1 on 2024-09-12 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_article_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-views']},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='journal_art_publish_aad2ca_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views'], name='journal_art_views_9b1069_idx'),
        ),
    ]
