# Generated by Django 5.1 on 2024-09-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_article_body_en_article_body_uk_article_intro_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
